displayName=Visual Tick Cursor
author=PureIllenium
description=A plugin to change the default window cursor based on defined colors and set tick intervals.
tags=
version=
plugins=com.example.VisualTickPlugin
build=standard
